baseURL = 'https://umi4.life/'
locale = 'en-us'
title = "UmiLife's Blog"
description = "test"
theme = 'reimu'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup.highlight]
guessSyntax = true
noClasses = false